import type { Metadata } from "next";
import { Archivo } from 'next/font/google'
import { Inter } from "next/font/google";
import "./globals.css";
import "./styles.css"
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
const inter = Inter({ subsets: ["latin"] });
const archivo = Archivo({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-archivo',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={archivo.className}>
        <Toaster></Toaster>
        {children}
        </body>
    </html>
    </ClerkProvider>
  );
}
